#!/bin/bash
set -euo pipefail

LOG_TAG=update-hosts
BLOCK_LIST_URL=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
HOSTS_FILE=/etc/hosts
BLOCK_LIST_FILE=/etc/hosts.blocklist
CUSTOM_HOSTS_FILE=/etc/hosts.custom

function log {
    echo $1 | systemd-cat -t $LOG_TAG
}

function hosts_write {
    echo $1 >> $HOSTS_FILE
}

log "Starting update hosts job"

if [ ! -f $CUSTOM_HOSTS_FILE ]; then
    log "No custom hosts file found at $CUSTOM_HOSTS_FILE; aborting"
    exit 1
fi

log "Downloading block list"
curl $BLOCK_LIST_URL > $BLOCK_LIST_FILE
log "Download complete"

log "Building combined hosts file"
echo "### HOSTS FILE AUTOGENERATED BY UPDATE-HOSTS SCRIPT ###" > $HOSTS_FILE
hosts_write " "
hosts_write " "
hosts_write "#############################################################################" 
hosts_write "#----- Start of custom hostsfile config ($CUSTOM_HOSTS_FILE)"
hosts_write "#############################################################################" 
cat $CUSTOM_HOSTS_FILE >> $HOSTS_FILE
hosts_write "#############################################################################" 
hosts_write "#----- End of custom hostsfile config"
hosts_write "#############################################################################" 
hosts_write " "
hosts_write " "
hosts_write "#############################################################################" 
hosts_write "#----- Start of downloaded blocklist config ($BLOCK_LIST_FILE)"
hosts_write "#############################################################################" 
cat $BLOCK_LIST_FILE >> $HOSTS_FILE
hosts_write "#############################################################################" 
hosts_write "#----- End of downloaded blocklist config ($BLOCK_LIST_FILE)"
hosts_write "#############################################################################" 
log "Hosts update complete"
